name: dnexus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Base de datos
  postgres: ^3.1.1
  
  # Estado y navegaci√≥n
  provider: ^6.1.1
  go_router: ^12.1.3
  
  # Almacenamiento
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI y utilidades
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  crypto: ^3.0.3
  
  # Validaciones
  formz: ^0.6.1
  
  # JSON y serializacion
  json_annotation: ^4.8.1
  
  # Logs y debug
  logger: ^2.0.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
